apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-app
  labels:
    app: tic-tac-toe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe-app
  template:
    metadata:
      labels:
        app: tic-tac-toe-app
    spec:
      containers:
      - name: tic-tac-toe-app
        image: rohitmarathe/tic-tac-toe:latest
        ports:
        - containerPort: 3000